openapi: 3.0.0
info:
  title: PeopleAPI
  description: Simple API that returns People based on Affiliation
  contact:
    email: intdev@apu.edu
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
tags:
- name: developers
  description: Operations available to regular developers
paths:
  /ping:
    get:
      tags:
      - developers
      summary: receive a pong response from the server
      description: |
        By going to the ping endpoint, the server
        will send pong if the request is succesful
      operationId: getPong
      x-exegesis-controller: pingController
      responses:
        "200":
          description: receive 'pong' from the server
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pong'
components:
  schemas:
    Pong:
      type: string
